[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "package_module"
description = "A template for multicommand utilities"
requires-python = ">=3.12"
dependencies = [
    "",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
]
dynamic = ["version"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
xped_tools = ["py.typed"]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "black",
    "flake8",
    "isort",
    "mypy",
    "pytest",
]
test = [
    "pytest",
]

[tool.pytest.ini_options]
addopts = "-vv -ra --strict-markers --tb=short"
testpaths = ["tests"]

[tool.black]
line-length = 88  # Enforce the default value

[tool.setuptools_scm]
write_to = "src/template_module/version.py"
write_to_template = """
# This file is auto-generated by setuptools-scm. Do NOT edit this file.
__VERSION__ = "{version}"
"""

[[tool.mypy.overrides]]
module = "networkx.*"
ignore_missing_imports = "True"

[project.scripts]
xped = "template_module.cli:main"